Repository legesher/tree-sitter-legesher-python, pull requests merged in 2019-10, with the labels that each got.

#20 Update README.md
  README.md
Labels: Hacktoberfest

#26 Add contributing.md file
  CONTRIBUTING.md
Labels: 📖 Opportunity: Documentation

#30 Added unibeautifyrc.json
  unibeautifyrc.json
Labels: 💻 Opportunity: Code
