Repository legesher/tree-sitter-legesher-python, pull requests merged in 2019-11, with the labels that each got.

#32 GitHub config and update all-contributors
  .all-contributorsrc
  .github/FUNDING.yml
  .github/ISSUE_TEMPLATE/ADD_DIALECT.md
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
  .github/ISSUE_TEMPLATE/REVIEW_DIALECT.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/config.yml
  .github/language-conventions.md
  README.md
  package.json
  script/known_failures.txt
Labels: 📆 Opportunity: Project Management

#39 Bug fix for GitHub actions PR
  .github/actions/commit-issue-action/entrypoint.sh
Labels: Type: Bug, 🐛 Opportunity: Bug

#41 version update from tree-sitter-python master
  corpus/literals.txt
  corpus/statements.txt
  grammar.js
  package.json
  properties/highlights.css
  queries/highlights.scm
  script/known_failures.txt
  src/grammar.json
  src/highlights.json
  src/node-types.json
  src/parser.c
  src/scanner.cc
  src/tree_sitter/parser.h
  template/corpus/expressions-template.txt
  template/corpus/literals-template.txt
  template/corpus/statements-template.txt
  template/examples/compound-statement-without-trailing-newline-template.py
  template/examples/crlf-line-endings-template.py
  template/examples/mixed-spaces-tabs-template.py
  template/examples/multiple-newlines-template.py
  template/examples/python2-grammar-crlf-template.py
  template/examples/python2-grammar-template.py
  template/examples/python3-grammar-crlf-template.py
  template/examples/python3-grammar-template.py
  template/examples/python3.8_grammar-template.py
  template/examples/simple-statements-without-trailing-newline-template.py
  template/examples/tabs-template.py
  template/examples/trailing-whitespace-template.py
  template/grammar-template.js
  template/properties/highlights-template.css
  template/src/highlights-template.json
Labels: 🚧 Opportunity: Maintenance
